### ISSUE TITLE
Update Packagist with the new repository URLs

### ISSUE THREAD

**Issue by benlk** [npr/pmp-php-sdk#35]
https://packagist.org/packages/publicmediaplatform/pmpsdk still has the following links set:

- repo: https://github.com/publicmediaplatform/phpsdk
- homepage: https://github.com/publicmediaplatform/phpsdk
- source: https://github.com/npr/pmp-php-sdk/tree/master
- issues: https://github.com/npr/pmp-php-sdk/issues

**Comment by scottsmith130** [comment]
https://github.com/npr/pmp-php-sdk is the new location for the repo, so I guess just the repo and homepage links need to be updated?

**Comment by scottsmith130** [comment]
All the URLs should be updated now
