### ISSUE TITLE
Outdated Symfony requirement in Composer.lock means that pmpsdk.phar is shipped with tests that don't run in PHPUnit 7

### ISSUE THREAD

**Issue by benlk** [npr/pmp-php-sdk#36]
Travis CI runs tests using the following PHPUnit versions:

PHP 5.6: PHPUnit 5.7.23
PHP 7: PHPUnit 6.4.3
PHP 7.1: PHPUnit 6.4.3
PHP 7.2: PHPUnit 7.0.2

When running tests for https://github.com/npr/pmp-wordpress-plugin/pull/131, many builds fail because of the error described at https://github.com/INN/pmp-wordpress-plugin/issues/6 : 
> PHP Fatal error: Class 'PHPUnit_Framework_TestCase' not found in /tmp/wordpress/tests/phpunit/includes/testcase.php on line 15

This is because PHPUnit 6 namespaced its code, which led to the following note in the release notes for PHPUnit 6: https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-6.0.0:
> Backwards Compatibility Issues
> PHPUnit's units of code are now namespaced. For instance, `PHPUnit_Framework_TestCase` is now `PHPUnit\Framework\TestCase`

Fixes:

- [ ] update the PMP PHP SDK to use a newer version of Symfony
- [ ] repackage
- [ ] push to the Composer Packagist repository

**Comment by scottsmith130** [comment]
Mostly likely the culprit is Guzzle (or at least the pretty outdated version of Guzzle this SDK still uses).

**Comment by benlk** [comment]
Since https://github.com/npr/pmp-php-sdk/blob/master/composer.json doesn't explicitly list Symfony, that's probably true. This issue duplicates https://github.com/npr/pmp-php-sdk/issues/34, then.

**Comment by benlk** [comment]
Reading the Guzzle upgrade docs https://github.com/guzzle/guzzle/blob/master/UPGRADING.md , it looks like upgrading from Guzzle 3.4 to a newer version may also fix https://github.com/npr/pmp-wordpress-plugin/issues/128 because it removes the cURL dependency, but that upgrade will potentially require refactoring some of the PMP PHP SDK, and will bump the minimum PHP version to at least 5.4.

**Comment by scottsmith130** [comment]
It will definitely require some refactoring of the SDK, which is the main reason we haven't done it yet.

**Comment by scottsmith130** [comment]
We'll be addressing this with #34 since upgrading Guzzle should resolve this too.  We'll be going to Guzzle 6.3, which I believe requires PHP 5.5.  Since that's not backward compatible change we'll be bumping the SDK version up to 2.0.0 with that upgrade. Which feels wrong to me given no other functionality is changing, but I guess that's semantic versioning for you.

**Comment by benlk** [comment]
That makes sense to me.
